### PR TITLE
Better Build & Release Mechanism

### PR DESCRIPTION
**Pull request by kyle-west**
@lukasoppermann this should do the trick (#495). 

I added a new feature `npm run release` that automates the process we talked about. Now the `dist` folder is still outside of version control, but present in the releases. Feel free to let me know what you think, and change the script to better suit your needs. 

Proof that it works can be found in my fork: https://github.com/kyle-west/html5sortable/releases/tag/v0.9.12 . This v0.9.12 release was made using `npm run release`.

### CODE REVIEW

**Comment by kyle-west** [comment]
@lukasoppermann I know you said in #495 that there is a modification you would like to have made to this. What is it exactly? Did you want it to run the release script right after `npm version`? I could try and see if I could get that to work for you.

**Comment by lukasoppermann** [comment]
Hey @kyle-west, that would be awesome.

So currently I do the following:

1. `npm version {patch|minor|major}` (this also increases the version number in the package.json)
2. the preversion, version and postversion scripts do some tests and add stuff to docs, which you have as well
3. than with `npm publish` I publish it to npm

I think you have everything covered apart from `npm version`, so if you can add this and remove the preversion, version and postversion, that would be great.

**Comment by kyle-west** [comment]
So I hope this is what you are meaning. I made it so that the release script runs the `postversion` and got rid of the `preversion` and `version` scripts because my script does the same things.

**Comment by lukasoppermann** [comment]
👍 Thank you

**Comment by lukasoppermann** [comment]
Hey @kyle-west, sorry it took so long to merge. However I think it does not work somehow. I did a release, but the latest release branch does not have the dist folder.

**Comment by kyle-west** [comment]
That's really odd. It worked on my fork. But then again my fork is not hooked up to NPM.

**Comment by kyle-west** [comment]
Did the script not run? Or was there an error? Does `npm run release` do anything?

**Comment by lukasoppermann** [comment]
Hey, now it did work. I reset everything and now it worked fine. So it was a false alarm. Thanks anyway, works like a charm now. 👍

**Comment by lukasoppermann** [comment]
Okay, @kyle-west we do have an issue though. Because this is now on the postversion, the npm release does not get the `dist` folder. I think we need to split the script into 2 parts, one for the `npm preversion` and one for the `npm postversion`

**Comment by kyle-west** [comment]
I see. Maybe we should add the following line to the end of the [`make-release.sh` script](https://github.com/lukasoppermann/html5sortable/blob/master/make-release.sh) to automatically publish the release from the distributed branch. 

```sh
npm publish folder .
```

Or we could do a similar thing and publish off of the GitHub tarball.

```sh
npm publish tarball "https://github.com/lukasoppermann/html5sortable/archive/$releaseVersion.tar.gz"
```

**Comment by lukasoppermann** [comment]
I think publishing off the tarball might be the best. So adding 
```
npm publish "https://github.com/lukasoppermann/html5sortable/archive/$releaseVersion.tar.gz"
```

Should be it. Do you want to send a PR?

Also do you think we could make it possible that a github release is automatically created from teh script? https://developer.github.com/v3/repos/releases/#create-a-release

**Comment by lukasoppermann** [comment]
I fixed it. There was another issue. `npm version xyz` created a tag. In the script you did not use the -f flag to overwrite the tag. Instead the initial tag was used, which did not contain the `dist` folder.

**Comment by kyle-west** [comment]
Great! I am glad you got it. It was nice working with you on this.

**Pull request merged**
