### PR TITLE
Detach dragged element from DOM while dragging.

### PR DESCRIPTION
**Pull request by ncjones**
This ensures styles for :first-child and :last-child are applied as expected for remaining list item elements such as when a Bootstrap List Group is used as the sortable list.

### CODE REVIEW

**Comment by ncjones** [comment]
I've just realised this is broken for a list with just a single item. I'll try to fix this soon.

**Comment by lukasoppermann** [comment]
Any news here?

**Comment by ncjones** [comment]
Sorry, the project I was using this for was put on hold so I never did the fix. Someone else will have to pick this up if it's desirable.

**Comment by lukasoppermann** [comment]
Closing due to inactivity.

**Pull request closed without merging**
