### PR TITLE
[Issue] Unable to drag & drop items to a shorter list without having to scroll

### PR DESCRIPTION
**Pull request by marrouchi**
Hi,

There is a problem when trying to move a draggable item from the bottom of a long list (A) to another shorter list (B), the placeholder stuck in A list even if the dragged item is over the B list. It works when the B list is empty, but if it contains at least one item then you need to scroll up and put the mouse pointer over one of the items.

https://jsfiddle.net/L247db7h/

Regards,

### CODE REVIEW

**Comment by lukasoppermann** [comment]
Hey, thanks for the PR.

Could you please:
1. Create a jsFiddle, Codepen, etc. to demonstrate the problem
2. jQuery is NOT used in the project anymore, so you solution does not work. You would need to revise it using vanilla js and the methods provided by this library

**Comment by marrouchi** [comment]
Done ! https://jsfiddle.net/L247db7h/

**Comment by lukasoppermann** [comment]
Hey, as I mentioned in the email your solution is based on IE special syntax which does not work for us.

Also it think a better solution would be to check if we are on a list with no item, or after the last item, and append it.

**Comment by lukasoppermann** [comment]
Closing due to inactivity.

**Pull request closed without merging**
