### PR TITLE
[WIP] refactor - eslint in all test files, fix some errors

### PR DESCRIPTION
**Pull request by jmuzsik**
Hi!

I mainly integrated additional typescript into the test files with a little refactoring. There is still much to do. 

Let me know if there is something you think I ought to particularly focus on. Otherwise I'll try to do additional refactoring and try to separate tests into folders/new files though it is more complicated with these files than the last one I did.

### CODE REVIEW

**Comment by lukasoppermann** [comment]
Hey @jMuzsik, I think you had a small misunderstanding. The `global` in `/* global describe,test,expect */` does not stand for the `global.body` variable but tells eslint that whatever follows are "global" variables and thus standard will not complain about it not being there. So if you re-add it the `CustomEvent` error should vanish. You could also probably use `window.CustomEvent` to get rid of this issue. Standard complains about some other things you would need to fix before I can merge this.

I will look into it and give you some more feedback later. Additional refactoring would definitely be nice.
If you would rather focus on non-test-related issues something like #314 or #340 would be good. (Or any other issue you have a particular interest in). Help with the tests or any of those is very good and appreciated.

Thank you. 😃

**Comment by lukasoppermann** [comment]
Hey @jMuzsik it is still failing. Just in case you did not notice, you can run `npm test` or `npm run standard` and you will see all the issues locally.

**Comment by jmuzsik** [comment]
Ok, I understand, I won't push unless I see that it is working. It is WIP atm, thanks!

**Comment by lukasoppermann** [comment]
Hey @jMuzsik this is not what I meant. Feel free to push in-between versions as much as you want. 😉

**Comment by jmuzsik** [comment]
Ok, got it! I have a difficult time deciphering how to split these tests into different test files as I do not have a very clear idea of what part of the code base each file works in unison with.  So, I would not know how to structure them into different folders nor if I ought to do so.

Also, the code is quite concise already so I do not see much that I can do in terms of modularity. I think I'll work on integrating typescript into other files other then the test files after this. 

Also, I notice that typescript does not agree with the way in which the sortable function is declared seeing how `__testing` is continually a type error within the tests. Reworking that function is also something I can attempt to work with.

Lastly, the type errors that exist other then the ones I fixed are complex. For example, some form of mixin or the like needs to be created to redefine the return value of `new CustomEvent('something')` so that these other properties are expected to occur.

**Comment by lukasoppermann** [comment]
Hey @jMuzsik,

getting more typescript into the code is definitely nice, especially for the non-test files.

The whole package will converted into an es6 module and `__testing` will be removed. So don't worry about this to much.

Currently the most interesting parts would be:
- add types to all functions to catch errors
- clean up the code base, adding comments and refactoring stuff into smaller functions that don't rely on external variables so they can be easily moved around and refactored

**Comment by jmuzsik** [comment]
Ok! I have a slight misunderstanding. What do you mean by catch arrows? Supposing you meant errors?

**Comment by lukasoppermann** [comment]
I should not be doing this at night 😆You are correct, I did mean to write errors.

**Pull request merged**
