### PR TITLE
Pass placeholder to sortstart handler

### PR DESCRIPTION
**Pull request by jnu**
Gives the `sortstart` handler access to the placeholder. Enables varying the placeholder appearance on the item being dragged. E.g. setting dimensions of placeholder to match dragging item in a list with unpredictably sized items.

### CODE REVIEW

**Comment by lukasoppermann** [comment]
As far as I see the only commit actually related to this PR is this one https://github.com/jnu/html5sortable/commit/ea72b2650826c033f17a7911b1b3bfb0cdf984bb if you could pull the current version and update your PR to just include this fix, I am happy to merge it.

**Comment by jnu** [comment]
I'll update when I get a chance this week

**Comment by lukasoppermann** [comment]
Thanks, please change only files & lines that you really need to and squash to one single commit with a descriptive name. This will make merging much easier.

**Comment by lukasoppermann** [comment]
Hey @jnu any news on this?

**Comment by jnu** [comment]
closed in favor of #151

**Pull request closed without merging**
