### PR TITLE
Move the 'use strict' declaration inside the plugin scope.

### PR DESCRIPTION
**Pull request by armandabric**

### CODE REVIEW

**Comment by lukasoppermann** [comment]
This is a duplicate of #59.

**Comment by armandabric** [comment]
The #59 introduce unnecessary change in the file: https://github.com/voidberg/html5sortable/pull/59/files#diff-8a5cc1d77050a32408094212e0822631L124 and https://github.com/voidberg/html5sortable/pull/59/files#diff-8a5cc1d77050a32408094212e0822631L140

**Comment by lukasoppermann** [comment]
I do agree, but maybe it would be better to ask the author to change his PR?

**Comment by eirikhm** [comment]
+1

Well, #59 suggests using this, so you can go ahead and merge.

**Comment by lukasoppermann** [comment]
Thanks, merged.

**Pull request closed without merging**
