### PR TITLE
Fix non-handles acting as handles.

### PR DESCRIPTION
**Pull request by lizzielizzielizzie**
Elements with draggable="true" initiated sorting, regardless of whether
or not they were the intended handle.

### CODE REVIEW

**Comment by lizzielizzielizzie** [comment]
As before, this should resolve issues #181 #166 and #147

Additionally you mentioned commiting any changes I made to the angular file, but it doesn't appear that any change is necessary. In all fairness though, I have literally no experience with angular

**Comment by lukasoppermann** [comment]
Hey @NickWer there should be no change, your are right. I thought there was, because previously you committed the angular file from `dist` but this was only due to it being recompiled with the new main source file.

I will check it out later and merge it in. Thank you for the contribution!

**Comment by lukasoppermann** [comment]
Hey, I checked it out, thanks. I would like to merge the PR, however, I would need to ask you to do the following before I can merge it:
- correctly indent the code https://github.com/voidberg/html5sortable/pull/202/files#diff-f42dd2e6f1fc935a2fd8a4911d6dfb1aR286
- if possible, add the cases described in #181 #166 and #147 to the `index.html` so as to verify they are really solved by this.

Thanks a lot,
Cheers

**Comment by lukasoppermann** [comment]
Ping @NickWer

**Comment by lizzielizzielizzie** [comment]
I addressed the items you mentioned, as well as updated them to meet the requirement that jquery be removed. Unfortunately I had to remove the test cases I had written, as I was unable to simulate a dragstart event on the handles, but added a test case to the index.html

Note that what may seem like (at least it did, to me) an extraneous ondragstart method added to index.html, [is required to actually cause the event to fire](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable).

**Pull request merged**
