### PR TITLE
allow handle in shadowRoot

### LINKED ISSUE #487: support shadowRoot handlers
It would be great to be able to also query shadowRoot when specifying handlers. This would be useful for instance when we are using `html5sortable` with Polymer (2 or 3): 

```html
<dom-module id="custom-drag-wrapper">
  <template>
      <iron-icon id="drag" icon="editor:drag-handle" alt="drag me"></iron-icon>
     <slot></slot>
  </template>
</dom-module>
```

and then : 
```js
 // initiate sortable with handler in shadowRoot:
 sortable( ..., {handle: '#drag'});
```

Submitting a PR soon.

### PR DESCRIPTION
**Pull request by christophe-g**
Closes #487 

Adaptations required to allow handle in shadowRoot:
- Event re-targeting  (https://gist.github.com/praveenpuglia/0832da687ed5a5d7a0907046c9ef1813#events-in-shadow-dom) : event.target might not be the real initial event target, hence the `getEventTarget` method.
- document-fragment does not have a parentElement (https://gist.github.com/praveenpuglia/0832da687ed5a5d7a0907046c9ef1813#terminologies), hence the use of `event.composedPath()` in `findSortable` instead of looping up dom tree to find sortable. 

Tests are passing, no time not to write new test for this feature. 

In case you are interested, I can PR a Polymer 2.0 port (actually rewrite) of https://github.com/rodrigosancho/polymer-html5sortable that would contain a demo testing this new feature.

### CODE REVIEW

**Comment by lukasoppermann** [comment]
Hey, yes please send a polymer 2 port. 👍

**Comment by christophe-g** [comment]
> Hey, yes please send a polymer 2 port.

Cool, I'll do that early next week.

**Comment by lukasoppermann** [comment]
Hey, can you do me a favor and remove all compiled files from the PR? So send only the ones in `src`. I thought I could delete them from the PR but this is actually saying a "delete this file".

Thanks.

**Comment by christophe-g** [comment]
@lukasoppermann - sure. 

Should build files not be git-ignored ?

**Comment by lukasoppermann** [comment]
Thanks.

Well the issue with `.gitignore` is that I need to be able to push those file to `master` when doing a new release.

I know of no way to ignore files but let me push them to master. 😞

**Comment by christophe-g** [comment]
@lukasoppermann  - understood. 

I am not an npm expert, but I think you can whitelist files that need to be included in the release package by adding : 
```
“files”: [“build/**/*”]
```
in package.json, and still let git ignore them (https://itnext.io/step-by-step-building-and-publishing-an-npm-typescript-package-44fe7164964c)

**Comment by lukasoppermann** [comment]
Ahh, so you are saying never push them to master but add them to npm? I'll investigate that. 👍

**Comment by lukasoppermann** [comment]
Hey @christophe-g could you update the PR so I can merge it? Thanks.

**Pull request merged**
