### PR TITLE
Revert "Fixed a placeholder bug, and a minor typo"

### PR DESCRIPTION
**Pull request by lukasoppermann**
Reverts voidberg/html5sortable#217

### CODE REVIEW

**Comment by thomasmattheussen** [comment]
Any reason why this has been reverted? I'm suffering from the same problem as in https://github.com/voidberg/html5sortable/pull/217

**Comment by lukasoppermann** [comment]
Yes, it broke the build. Can you create a ticket for this again? Sorry for the inconvenience. If you could send in a PR with tests that would be great.

**Comment by lukasoppermann** [comment]
Hey @thomasmattheussen, 

I rebuild his PR and added it. Can you please test if your problem is solved? But please make sure to pull from master, it is not tagged yet.

**Comment by thomasmattheussen** [comment]
I fixed it by creating the element and supplying that, instead of a selector. A solution I came up with right after posting this 😅 

But yeah, reverting this once more does seem to fix the original problem :)

**Pull request merged**
