### PR TITLE
Potential change to address Issue#456

### PR DESCRIPTION
**Pull request by Lemonsavery**
https://github.com/lukasoppermann/html5sortable/issues/456

### CODE REVIEW

**Comment by Lemonsavery** [comment]
I encountered the same issue as described in #456, and this was part of my fix for it. My issue would occur while using Chrome, but not while using Edge.

**Comment by lukasoppermann** [comment]
Hey @Lemonsavery 
thank you very much for the PR. I will have to look into it to to make sure it has not repercussions and hope to be able to merge it very soon. Great. 👍

**Comment by lukasoppermann** [comment]
Hey @Lemonsavery can you please explain the issue it is solving again? I have the feeling the issue mentioned in the ticket persists, but this may be due to me not really getting how to reproduce it. 😁

**Comment by Lemonsavery** [comment]
@lukasoppermann Here are two gifs of rows being dragged and dropped quickly/normal. Drag events are printed to Chrome DevTools console. When dragged and dropped too quickly, the 'drop' event can occur before the placeholder row is in place. insertNode() then tries to use the placeholder as referenceNode, but referenceNode.nextElementSibling is null, **so the dragged row vanishes**. Then, later, the placeholder row is created.
| buggy drag | correct drag |
|:---:|:---:|

**Review by lukasoppermann — APPROVED** [review]

**Pull request merged**
