### PR TITLE
Move "use strict" inside closure

### PR DESCRIPTION
**Pull request by dstelljes**
This is a really picky fix, but it keeps this plugin from messing stuff up when it's concatenated with other files that don't work under strict mode.

### CODE REVIEW

**Comment by hjellek** [comment]
It would be better to remove your style changes and only include the moving of "use strict" since that is what your issue is about.

Other than that, +1, need this fix myself.

**Comment by dstelljes** [comment]
You're right, I should have titled this differently. The other changes are just two inconsequential things that the linter caught. If there's any activity on the repo and it ends up making any difference, this can be closed and #79 merged.

**Comment by lukasoppermann** [comment]
Hey @dstelljes, voidberg got me access to the repo, so we will see some action in the repo now. :)

Fixed in 7fb6b29aa5b5236cbc87e6cbef5882a9573a1d38

**Comment by dstelljes** [comment]
Awesome, thanks!

**Comment by lukasoppermann** [comment]
Sure, thanks for bringing it up. :+1:

**Pull request closed without merging**
