### PR TITLE
refactor - internal test file put in own folder and made more readabl…

### PR DESCRIPTION
**Pull request by jmuzsik**
Ok, I did way too many git commands that made things irrevocable confusing. So I reset my fork to be connected to `upstream/master`, prior to doing so saved what I did previously and simply copy/pasted.

Hope this is fine now! Thanks... I'll put time to understanding rebase as soon as I can.

### CODE REVIEW

**Comment by lukasoppermann** [comment]
Sometimes this is the best and easiest option. Rebase seems complicated, but once you wrapped your head around it, it is actually quite simple. Talking from personal experience here. 😁

One thing I noticed already is that you committed the _attached file but only with one empty skipped test.

I'll have a look and get back to you. Thank you.

**Comment by lukasoppermann** [comment]
Thanks. 👍

**Comment by jmuzsik** [comment]
@lukasoppermann I'll continue working on the tests unless there is something else you'd prefer me to do

**Comment by lukasoppermann** [comment]
Hey @jMuzsik, that sounds good. 👍 Thank you. Especially now that the code base is changing a lot, it will be crucial to have a solid and easy to understand test base.

**Pull request merged**
