### PR TITLE
Make handles draggable to allow selection in firefox

### LINKED ISSUE #46: Select text in input not work with Firefox
Hi !
Nice to see this project with new mantained :)

We have old bug with this code. When you use with this sortable, you cannot select text in `input` or `textarea` fields.

What I can to do for fix this?

Thanks !

### PR DESCRIPTION
**Pull request by splagemann**
Fixes #46

### CODE REVIEW

**Comment by voidberg** [comment]
Merged, thanks!

**Comment by KingYes** [comment]
Good job :)

**Comment by splagemann** [comment]
@voidberg Can you please release a new version to make it installable via bower! Thanks!

**Comment by voidberg** [comment]
Done.

**Pull request merged**
