### PR TITLE
Support for fixed items

### PR DESCRIPTION
**Pull request by jnu**
Adds support for static list items, i.e. items whose positions remain fixed when the sortable items are being moved. The sortable items will reorder around the fixed items.

Also adds a `sortchange` event .

### CODE REVIEW

**Comment by lukasoppermann** [comment]
Hey @jnu its an interesting idea, I think it has a bug though. Sometimes, when dragging to the last position the item is placed to the top of the list and there are 2 items at the top.

Also, can you please update your code to the current master and remove every change that is not vitally important? The more you change the more merge conflicts I get, so please do NOT build and only update the `html.sortable.src.js` and the `examples/index.html` file. Also please do not add multiple features, like the `sortchange`

**Comment by jnu** [comment]
I'll update and take a look at the bug when I get a chance this week. Thanks!

**Comment by lukasoppermann** [comment]
Thank you. Once you have it fixed, please squash this one as well to one commit, with a descriptive name and only the changes needed.

**Comment by lukasoppermann** [comment]
Hey @jnu any news here?

**Comment by lukasoppermann** [comment]
Closing due to inactivity.

**Pull request closed without merging**
