### PR TITLE
Avoid flicker when sorting. Fixes #162

### LINKED ISSUE #162: flicker when dragging between items
Recorded the issue: https://youtu.be/w7SHoj7elv8

### PR DESCRIPTION
**Pull request by tidyui**
Changed placeholder position to be based on element vertical middle and mouse position.

### CODE REVIEW

**Comment by tidyui** [comment]
I did not add any functionality, I simply altered the existing. My modification added one additional line of source code which is probably why the coverage dropped 0.2% :)

**Comment by lukasoppermann** [comment]
Hey, that is not an issue, however can you please remove all files but the src file from the PR?

So please only commit: `src/html5sortable.ts` thanks

**Comment by tidyui** [comment]
Sure! No problems!

**Comment by tidyui** [comment]
This did NOT turn out the way I planned :) For simplicity, let me close this pull request and open a new one.

**Pull request closed without merging**
